const GAME_LEVELS = [
   ["                                                                  ",
    "                                                                  ",
    "                                                                  ",
    "                                                                  ",
    "                                                                  ",
    "                                                                  ",
    "                                                                  ",
    "                                                                  ",
    "                                                                  ",
    "  @     o      ooo       xxxx                              oooo   ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                                                                  ",
    "                                                                  ",
    "                                                                  ",
    "                                                                  "],
   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                  x                                                             ",
    "                  x                                                             ",
    "                  x                                                             ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                  oo                                                            ",
    "             xxxxxxxxx                                                          ",
    "                                                                                ",
    "                  oo                                                            ",
    "    xxxxx      xxxxxx!!!!!!!xxxxxxxx                                            ",
    "           v                                 v      v       v                   ",
    "                                                                                ",
    "  @     o      ooo       xxxx    xxxx                              =     oooo   ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                             !!!!!!!                                            ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                "]
    ];